### ISSUE TITLE
Make it so you can move faster in water without a boat

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#1]
I often find myself in water and whenever I do it massively slows me down. _this might be me coming from minced one but I enjoyed basically being able to use water for faster travel_

_If you make it so you can dodge in the water or just sprint swim fast that would work._

**Comment by uthw** [comment]
Are you on version 0.0.1 or 0.1.0? If you're playing on the former this is probably because of the temperature mechanics which I disabled in the update
