### ISSUE TITLE
Any tetra Knife Quest is broken

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#100]
The name explains it

**Comment by uthw** [comment]
Okay, I fixed the shortblade quest and it now completes correctly according to my testing, but from now on I want you to fix issues in the tetra quests yourself since you made them in the first place

**Comment by Guineapigboyx** [comment]
I will fix any of the tetra quests/bestiary quests. I will also send you mob descriptions if I end up finding one that's not inside of the bestiary.

**Comment by uthw** [comment]
👍👍
