### ISSUE TITLE
Decrease damage of pikes from spartan and tetra

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#106]
For being the longest ranged weapon in the game they deal too much damage.
_A diamond pike with a warped light handle has over 2 speed and does almost 8 damage with a range of +2 (aka 5)_

I like the idea of haveing a weapon with that much range but I think they should have half or less than their current damage. I think they should act as a long ranged poking tool to keep something away insted of a weapon to quickly kill enemies.
(Same speed/range but they have pitiful damage)

**Comment by uthw** [comment]
Alright
