### ISSUE TITLE
Pikerang is underpowered

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#107]
You need to heart of diamond to make one what requires you to find a mob what activity runs and disappears as soon as you get anywhere close in a dark cave. For getting a pikrang you basically get a pickaxe with longer range and the only boomerang what will actually come back to you after thrown.

_They should be changed to at least deal similar damge to the sparten boomerrangs if anything._

**Comment by uthw** [comment]
The pickarang is intended for mining, not combat. Based on how you described it, it is working as intended.

**Comment by Guineapigboyx** [comment]
im saying it to hard to get for what you get out of it.

like even for mineing it can only break one block at a time and with it needing to move to block and back makeing it very slow.
