### ISSUE TITLE
Thrown weapons can be hard to find.

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#108]
When you throw a weapon iit can be hard to find sometimes. it is possible to find it with the minimap but it has the same dot as a lot of difficult items what can make it hard to find sometimes. This could also be fixed by giving items like smarten daggers or tomahawks or boomerangs a icon.

This apply to items the wild hunt boomerang and some spartan weapons and some tetra weapons.

**Comment by uthw** [comment]
I will see about adding map icons but the way I find lost thrown weapons is by holding down tab, which causes map icons to show their names below them. From there you can find the one that says "entity.spartanweaponry.boomerang" or whatever weapon you threw.

**Comment by Guineapigboyx** [comment]
Yeah i know about the tab thing the ishue is that the names are not easy to read like (teta:modular_thrown_tomahawk)

**Comment by uthw** [comment]
i was able to make icons for all the throwable items from spartan weaponry and the boomerang from hunter's return. i tried it with tetra but the icon wouldn't show up no matter what i did so for now you'll have to use tab for that
