### ISSUE TITLE
Tetra enchant fix was only applied to swords

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#109]
axes (2 head) [there are a few more but all of them are related with mineing none with damage]
![image](https://github.com/user-attachments/assets/16ffd174-2db9-4349-b0db-955253454934)

Shovels (1 head)
![image](https://github.com/user-attachments/assets/cfe6e184-f314-445e-a796-ba381023c38c)

polearms
![image](https://github.com/user-attachments/assets/7c892e02-89ff-4df2-a9d0-c585dba26099)

**Comment by uthw** [comment]
Double-headed is working as intended, they aren't intended to get sword enchantments. The fix only isn't applying to single-headed and polearms.
