### ISSUE TITLE
Temperature improvement suggestion thread

### ISSUE THREAD

**Issue by uthw** [uthw/Mincemeat-2#112]
This is a place where you can put any ideas or problems you have with the temperature system added in v0.4.8

Possible ideas include:
- items that should be sewable into your armor to get weather resistance (I already added a few dozen of these)
- items that should be usable in a boiler/icebox/hearth to change the surrounding temperature
- blocks that should increase or decrease the temperature around them
- changes to the temperatures of specific biomes or dimensions
- changes to the temperature system in its entirety
- straight up removing the mechanic because you think the modpack is better without it

**Comment by Guineapigboyx** [comment]
Lower The speed reduction given by cold.
- It makes it difficult to get out of the place what you are freezing to death in.
- It is annoying to be slowed down (especially in places like the ice maze where you are always cold)

Put a description on the water skin. explaining how to properly use the item

Make a quest explaining the Insulation levels (or at least that's what i think these colors are)
![image](https://github.com/user-attachments/assets/3ec98f22-3cc8-4577-a047-64fdef79a243)
![image](https://github.com/user-attachments/assets/c2317f1d-a216-43e6-9fdd-745481aeec40)
![image](https://github.com/user-attachments/assets/0146b952-2a45-44e6-a2b6-dadb2a58de5c)
![image](https://github.com/user-attachments/assets/4cb1d81c-aef7-4bf7-a218-d85d12456766)
![image](https://github.com/user-attachments/assets/99ee4b7d-e33a-4457-9684-a4b12298108e)

_Maybe_

Lower the amount of damage you take from the cold so you have a chance to get warm again before you die.

**Comment by Guineapigboyx** [comment]
Desert does not give enough heat.
- Not heating up fast enough 
- Cooling down at night

Because of both of those You never end up getting at critically hot temps.

**Comment by Guineapigboyx** [comment]
Ever-bright heat issues

There is nothing telling you that you should bring a sewing Machine or insulation. So a new player would be caught off guard by how col the ever bright is. You most likely want to also include you should come with leather armor and Caves are warm.

**Comment by uthw** [comment]
> Ever-bright heat issues
> 
> There is nothing telling you that you should bring a sewing Machine or insulation. So a new player would be caught off guard by how col the ever bright is. You most likely want to also include you should come with leather armor and Caves are warm.

I think getting thrown off balance by extreme weather in other dimensions is part of the experience. It ruins the surprise, so to speak, if they know about it in advance.

**Comment by Guineapigboyx** [comment]
Make it so rain does not make you super cold.
- You will freeze to death if it is raining and is night a in a lot of places (what is very inconvenient if you die)

Make it so you can sleep even if you are cold.
- If it is night and you die and try to to pass the night you can't
- You can't set your spawn in a place you think you may die or when far from spawn

**Comment by Guineapigboyx** [comment]
Make More structures produce heat/cold

Most progression structures like these
- Blue Skies dungeons
- Gatekeeper snowy houses
- Hunters house
- conjure theater

Other structures: 
- Sunbird arena
- Winter wagon
- Wizards Tower
- Apotheosis gem tower (IDK the name of it)
- Dragon nests
- Sunken City (water + cold is a deadly combo)
- Stray tower (The only reason is for how common it is and it could act as a pit stop to heat up at)
- Fire watch tower (nova structures)
- Tavern (Nova structures)
- Castle

Many more structures should be warm and are not but I don't know them off the top of my head. Also, a lot of structures like camps have campfires that heat them or are large enough to have passive heating.

**Comment by Guineapigboyx** [comment]
Make More Blocks produce heat/cold

Blocks:
- Blue fire (Fire that is made by using a flint and steel in the everbright)
- Dark fire (Fire that is made by using a flint and steel in the everdawn)
- Jumbo furnace
- Horizonte forge
- snowcap oven
- Candle (For the reason that most house-style structures have them so this would be an easy way to make them hospitable)
- Soul Lanterns (The same reason as the candles but a way to cool down in the nether)
- Stove
- Oven
- Blackstone Stove
- End stove
- Golden moth jar
- Waystones (Make the sandy ones cool)

----------------------

Maybes
- Normal lanterns (same reason as candles but this could be abused since they are easy to make and a player is more likely to use them more commonly)
- Loot chests/barrels (For the same reason as Candles but it would be a surefire way to limit the Temperature effects to just structures since most have these.) But the issue with adding these is that it will make ANY structure heat or cool)

-------------------------

There is most likely some I forgot but these are the ones That would make sense They heat or cool

**Comment by Guineapigboyx** [comment]
Tech mod blocks that should change temps: I don't see these as much as being They help with heating or cooling your home but more as a by-product you need to deal with if you use them.
- primitive alloy smelter 
- alloy smelter
- External heater
- blaze burner (if heated or superheated even better)
- Boiler heater (create new age)
- Heat pump
- Heat pipe
- Heat sink (if possible in its cold mode it cools and in the hot mode it makes heat)
- liquid Superheated sodium
- Superheating element
- Heat collector
- Coke oven
- Steam engine
- Sterling dynamo
- Air compressor (pneumatic craft)
- Pyrolyzer (it has pyro in it so I'm adding it to this list)
- Thermopumatic Processing plant

If possible the ones that could have an on state should only make heat when on.

There is more that could be on this list (even ones that would not make sense to make heat but would be interesting to need to deal with its by products)

**Comment by uthw** [comment]
I added most of your suggestions. Leaving some out since I'm not on board with structures like wizard towers and hunter houses changing the temperature. Also, some blocks like the alloy smelters and heatsink don't have block data for whether they're lit/heated/active/etc. so I left them out. 

I'm a little cautious about allowing sleep regardless of temperature since it bypasses the getting cold at night mechanic, but I listened to you for now since it must get irritating as a player.

**Comment by Guineapigboyx** [comment]
At the bottem of everdawn worlds there is a large layer of lava. Becuase of this it makes the inside of the bottem layer of the poison duneon extremely hot like 300°. I don't know a good way to fix this unless you can make it so it is temperate (not to hot or to cold) in the poison dungeon or give the grace buff when in the duneon or near the boss.

In my play through there was 1 half of boss area far from the lava but I feel this could be a issue.

**Comment by Guineapigboyx** [comment]
The effects of hot is more potent than cold. Cold is a lot more common also since more biomes are very cold than very hot (like anything with water is could be cold) It feels like hot should be more powerful because of its rareity.
