### ISSUE TITLE
Chnage the Info in craftpresence

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#116]
I think it would be a good addition to add a custom icon and Title
![image](https://github.com/user-attachments/assets/0282f00f-a20f-4cfd-a749-7a8d1d297550)

_I would not call this an issue but it is where things like this are stored so_ 🤷‍♂️

**Comment by Guineapigboyx** [comment]
Side note
In severs it does not say _Mincemeat2-0.X.X_ it says the server's Motd

**Comment by uthw** [comment]
Added custom craftpresence integration with icons for the Aether and Everbright/Everdawn. It's still basic and WIP but good to have something custom
