### ISSUE TITLE
Make it so you can't wear backpakcs as armor

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#119]
It's annoying when you try to equip a backpack by shift-clicking and it goes onto your chest plate slot instead of your back slot.
I checked it in the configs for sophisticated backpacks.

**Comment by uthw** [comment]
I don't see an option for this in the configs for Sophisticated Backpacks or Core, can you send me a screenshot of where you see the option?

**Comment by uthw** [comment]
Afaik this is probably not possible without editing the source code for Sophisticated Backpacks
