### ISSUE TITLE
Can't get ectoplasam / to rare of a drop

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#12]
Ectoplasam is hard to get but not for the reason that it is hard to find a grave yard. it is rare because ectoplasm seems to be a very rare drop from ghosts which spawn in the aforementioned grave yard after opening its chest. I killed 7 ghosts and i did not even get a single ectoplasm and it seems it can't appears in the chest also makeing it impossible to get ectoplasm.

In EMI it says it is a 50% chance of dropping 1 ectoplasm btu i think that may be wrong.

**Comment by uthw** [comment]
Wraiths drop ectoplasm, it's just not shown in emi
