### ISSUE TITLE
Thrasher should get a quest

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#124]
### Affected quests

Generateing power tech lv1

### Does it prevent you from progressing through the quests?

Yes

### If this is a bug, does it only happen in the latest version?

None

### If this is not a bug, is it a suggestion/feature request?

Yes

### Describe the issue

The thrasher mob found in the deep ocean does not have a quest. This is important because you need its teeth to make the Redstone furnace, which does not have a quest. Because of this, the player might not know where to find one or know how to kill one. This could be something as simple as adding a bestiary description (what you told me to not worry about its quest) And a pointer to it on the generating power quest.

Also, 2 tooth blocks for something as simple as a furnace that runs on RF is kind of expensive. for finding multiple of a rare mob that kills you pretty fast in the cold deep ocean where you freeze to death and there are deepling brutes and most of it being the ice maze the super cold place with many bosses. Also not to mention that it only spawns on the sea floor (not in caves) where you are unlikely to swim since you can only swim down there for a few seconds before you drown.

### Add additional context

I marked this as "Does it prevent you from progressing through the quests?" since it is unlikely a player would just be swimming around at the bottom of the cold deep ocean not in a cave and just run into it or know how to defeat it.

**Comment by uthw** [comment]
Thrashers are disabled so this isn't needed anymore

For the future, only click yes for "Does it prevent you from progressing through the quests?" if you're physically incapable of completing a quest or unlocking part of a chapter without going into the editor. E.g. a quest's completion criteria are bugged or a quest has incorrect dependencies.
