### ISSUE TITLE
Thrasher is even more of a inta kill after the fix

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#125]
This commit did not work
61e54672bcc289b77a20b431ea49f583e1e8a6d3

Now when the thrasher bites you it will lock your camera and will not allow you to hit it now even with a non-better combat weapon.

I show a video of it locking my camera. also, I did try before with a diopside pickaxe and it still did not allow me to escape.
https://github.com/user-attachments/assets/4dd5eb20-51ba-487c-b697-89689f7f7234

**Comment by uthw** [comment]
I went to investigate this and it seems like the Better Combat fix didn't work on thrashers. However, while experimenting with this, my game crashed multiple times pointing to Reliquary mod conflicting with the thrasher's pathfinding system. So for now I'm just going to disable thrashers and change all items related to them to use other items instead.
