### ISSUE TITLE
Blue skies 2nd bosses are to difficult

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#127]
Even with the help of the issue https://github.com/uthw/Mincemeat-2/issues/126# I still had a hard time killing both the the Starlit Crusher and the Arachnarch I still had a hard time killing them, Even tho i had almost full charoite gear and dual diopeside axes or for the Arachnarch a charoite with bane of atherpods 3. Also have eaten over 100 different foods.

The items you also should have the defeat them is not told. Those being the moonstone shield for the Arachnarch so it is not disabled for as long And the moonstone/soulbond spears to stun the the Starlit Crusher.

Starlit Crusher:
- To much hp
- Rush attack is to strong (idk if you can fix this)
   - Rush attack is way to fast (you basicly have to have phallax on your sheild or use a moter grappling hook)
   - It has no start up for you to predict
   - Does to much damage per hit for how fast it will hit you

Arachnarch:
- Nested spiders are very strong and will kill you fast

**Comment by uthw** [comment]
Fixed in dev (8210cca)
