### ISSUE TITLE
Graves should have a Map icon

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#128]
For a similar reason to the issue https://github.com/uthw/Mincemeat-2/issues/108. Its also easier than looking for the name/holding own alt for a while if you can't find it.

**Comment by uthw** [comment]
This will be included in the next version as it's not much of a commitment to add minimap icons. However, I'll remind you that Xaero's Minimap creates waypoints when you die, which is basically what you're asking for
