### ISSUE TITLE
Modded matrials have very low duribility

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#130]
Vinnla materials have higher or equal durability compared to even high-tier materials. For how hard some of these are to get they should be able to last a a bit longer without needing to put mending or high-level unbreaking. (Expesily since to repair some of these it would be very annoying to get the materials to do so)

This is a diamond helm for context
![image](https://github.com/user-attachments/assets/5adac59a-c667-4363-8f9f-69f9a8e93b09)

Sea serpent
![image](https://github.com/user-attachments/assets/d0c8119f-6fed-4db2-a917-9533290c886b)

Terra steel (end game natural magic)
![image](https://github.com/user-attachments/assets/974a81b3-b840-471a-b80f-1fb022cd6a92)

End game helmet (has only 100 more)
![image](https://github.com/user-attachments/assets/8cfc6395-c265-4c16-8790-cece17bc7d79)

Charoite
![image](https://github.com/user-attachments/assets/707ddfbe-6bb9-48a1-ae24-87239924d75b)

---------------------

This and non-end game gear Have barely any durability.

A few examples
![image](https://github.com/user-attachments/assets/a08f09be-4ef5-42d0-8361-ceb41456e386)
![image](https://github.com/user-attachments/assets/d9b379b4-e629-4958-b352-49d667050798)
![image](https://github.com/user-attachments/assets/404b02ba-2c24-4a20-83ef-eca16aca3b56)

**Comment by uthw** [comment]
A [script](https://github.com/uthw/Mincemeat-2/blob/master/kubejs/startup_scripts/items/durability.js) similar to the one from Mincemeat 1 already exists which doubles the durability of every item. I wrote it a long time ago and it has a lot of broken and commented-out code but if you look closely you can see it works as intended. 

This means items that don't have increased durability are probably hard-coded, meaning I can't do much about it unless the mod allows changing it in the config, which was the case for Spartan Weaponry.

I'll see what I can do but keep in mind I can't change the durability of all items.

**Comment by uthw** [comment]
Unbreaking is already very powerful. It's easy to get Unbreaking 4+ using an Enchanter or Tomes of Scrapping, and it costs no enchantment points to put on items.

**Comment by uthw** [comment]
Increased durability of tools from Mekanism. There's not much I can do for the other items you mentioned. If you find something else with low durability, comment it here and I'll see if I can increase it.
