### ISSUE TITLE
Magic Quest Mess-up!

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#131]
### Affected quests

Wicked Weave, Unholy Symbol, Ars Nouveau

### Does it prevent you from progressing through the quests?

Yes

### If this is a bug, does it only happen in the latest version?

None

### If this is not a bug, is it a suggestion/feature request?

None

### Describe the issue

Fairly certain the progression to Ars Nouveau is meant to come from Unholy Symbol, and not Wicked Weave

Currently it is tied to Wicked Weave which requires me to get a ghast tear (i cant do that this early) and that means in order to get source gem (the quest) I need to go to the nether, which seems arbitrary since I can just make source gems before all three quests mentioned in affected quests.

**Comment by uthw** [comment]
Wicked Weave is prerequisite for Ars Nouveau because it's used in the recipe for Novice Spellbook. I'll fix the ghast tear thing since that doesn't sound intended
