### ISSUE TITLE
Alchemy Progression is Wack

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#132]
### Affected quests

Blood Alter, Unholy Symbol

### Does it prevent you from progressing through the quests?

Yes

### If this is a bug, does it only happen in the latest version?

None

### If this is not a bug, is it a suggestion/feature request?

Yes

### Describe the issue

Alchemy table isnt a quest and requires the blood alter to make. 

would be nice to be able to start the blood alter quest a little sooner in progression and then have an alchemy table quest right before the unholy symbol quest, though its not required, id rather not retrace steps for quest progression

**Comment by Guineapigboyx** [comment]
This is just saying add a quest for the alchemy table sense you need to make a few items to get to ars.

**Comment by uthw** [comment]
You don't need an alchemy table to make the Unholy Symbol; that recipe is just quality-of-life for if you're later into progression and lose your original symbol. The way of getting an Unholy Symbol is documented in the quests Signs, Build an Altar, Second Chant, and Unholy Symbol in Supernatural Magic.
