### ISSUE TITLE
Seegmented quests for magic

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#136]
### Affected quests

Super natural magic and natures aura.

### Does it prevent you from progressing through the quests?

No

### If this is a bug, does it only happen in the latest version?

None

### If this is not a bug, is it a suggestion/feature request?

Yes

### Describe the issue

In super natural and natures aura you see everything at once I think it should be like tech and you only see parts.

### Add additional context

Tho I will admit sometimes it would be annoying since you can't see what you need to do to get into different magic mods. Like if you wanted to find out how to get source gem/ars nova you would be flying blind since you would not know you need to do ediloin first.

_The only thing like this in tech is thermal since you would not know how to start it until you do immersive engineering_

------------------

Maybe keep these quest visible at all times and put a subtitle on them that says do blank magic mod first.

![image](https://github.com/user-attachments/assets/067c9d15-689e-46ba-9bd6-2de8a91e2a6f)

![image](https://github.com/user-attachments/assets/dc2f93d1-9ac8-43bf-9e74-6b3258ac46e8)

**Comment by Guineapigboyx** [comment]
tho to my other commnt you could use the progression tab to find out what you need to do.
![image](https://github.com/user-attachments/assets/c61cbd8f-b42e-4db5-8843-1ef7f22009cb)

**Comment by uthw** [comment]
I don't plan on doing this. To extend on what you said in Additional Context, magic is less linear than technology, so the chapter benefits from always knowing where you can go to unlock another mod or make a certain item.
