### ISSUE TITLE
Xnet Prank?

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#141]
### Affected quests

Cables

### Does it prevent you from progressing through the quests?

Yes

### If this is a bug, does it only happen in the latest version?

None

### If this is not a bug, is it a suggestion/feature request?

None

### Describe the issue

What image?

![image](https://github.com/user-attachments/assets/ab3ad257-9aa2-4c34-bd9f-074a69b0060b)

### Add additional context

Ok I will admit this is funny and made me laugh the first time I saw it.

**Comment by uthw** [comment]
Those are placeholders from before I imported all the images from Mincemeat 1, not necessarily a prank but I'm glad you liked it.

Also, this does not prevent you from progressing through quests
