### ISSUE TITLE
Quests Not Specific Enough

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#143]
### Affected quests

Most Magic Quests

### Does it prevent you from progressing through the quests?

Yes

### If this is a bug, does it only happen in the latest version?

None

### If this is not a bug, is it a suggestion/feature request?

Yes

### Describe the issue

Add pictures or be more descriptive to magic quests. Me and Xavier took an hour trying to figure out Botania (we had to look up a guide)

I'm begging, it takes so damn long to figure out.

**Comment by Guineapigboyx** [comment]
This is not explained very well so I will in this comment.

This is closely related to issue https://github.com/uthw/Mincemeat-2/issues/133. The main thing is that there are some parts that seam simple when you understand them but if you don't are very confusing. 

Examples: crusibul edilon resipes what include storing. I'm going to use the leather resipe what takes 2 enchanted dust and a rotten flesh and 2 stirs for this.
So once I first tried was throwing in the Enchanted Ash waiting for it to Bubble/change color then throw in the rotten flesh wait for it to bubble then stir it twice. But that makes a failure. I also tried stirring it and waiting for it to bubble on each stir. And many other combinations. Eventually when I found out is I need to start as I throw in the rotten flesh then immediately stir it before a bubbles.
So it took me a really long time to figure out that you need to Stir before it bubbles. What didn't make sense to me at first since all the other steps I had to wait for it to Bubble.

Another example is when I was trying to transfer Mana from a man of producing flower to a Mana pool. First off I needed to First find out that I need to get a wand what doesn't even have a quest then link them together by right clicking on the Mana pool and the non pulse Mana distributor. And that the flowers automatically connected to the Mana distributor. And even after it started working I was unsure that it was actually working because it did not look like it was adding anything since the hypoiage is very slow. All of those steps I just sent up above we're not even mentioned in the quest, excluding the part that I need to connect the wand to a Mana distributor, not that I would need to get a different type of Mana distributor to make it as effective as possible or how to setup the flowers or how to even know if the pool is filling

Just call me on discord if your confused on what I'm trying to say since I myself and having a hard time explaining this issue.

**Comment by uthw** [comment]
The Botania quests are ported directly from Mincemeat 1 which had the Morph-o-tool so I could assume players already had a Wand of the Forest going in. This reminds me to add that mod since it ported to 1.20.1 recently. I was also in a hurry to get the entire chapter done in one day, which led to some rushed descriptions. I fixed several of them and added descriptions on how to use the wand, as well as an image for mana spreaders.

However, I don't see the problem with the description for the Eidolon crucible. The crucible uses audio queues to signify when a new step begins. I had no trouble making different items with it. If you play with sound off for whatever reason, or the sound is hard to hear, turn on subtitles and look for the brewing stand sound.

**Comment by Guineapigboyx** [comment]
> The Botania quests are ported directly from Mincemeat 1 which had the Morph-o-tool so I could assume players already had a Wand of the Forest going in. This reminds me to add that mod since it ported to 1.20.1 recently. I was also in a hurry to get the entire chapter done in one day, which led to some rushed descriptions. I fixed several of them and added descriptions on how to use the wand, as well as an image for mana spreaders.
> 
> However, I don't see the problem with the description for the Eidolon crucible. The crucible uses audio queues to signify when a new step begins, which is explained in the quest. I had no trouble making different items with it. If you play with sound off for whatever reason, or the sound is hard to hear, turn on subtitles and look for the brewing stand sound.

The thing with the crucible is when you stir it. It makes a ton a sense if you know it but it took me a ton of trial and error before I found out. Like what i thoght did it is that you should throw in the material wait for it to bubble then stir it then wait for it to bubble then stir it again. Or throw in the matorql wait for it to bubble stir it twice then I get the matiral.

It would help if you add something what just talks about the stiring in the crucible and that you do it at the same time as throwing something in.
