### ISSUE TITLE
Teletor Is very strong commpared to all other alex cave mobs

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#148]
Apart from that he floats and moves left to right making it harder to hit him. It also has a fast-ranged attack that is difficult to dodge. He kinda feels like a mini-boss but he spawns to offen to be one.

if your curios I was using a full set charoite armor(with lightweight) and tetra diopside weapons and a Tetra diamond tomahawk with a affix that allow it to do 14 damage.

**Comment by uthw** [comment]
Sounds perfectly fine to me. It's not supposed to be easy
