### ISSUE TITLE
Emi does not make it clear what mobs have special drops

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#149]
Gameplay drops. Many of these just need their section renamed like how Piglin bartering is. But a few have horrible gui's like seal barter trades so it would be nice if they were cleaned up.
![image](https://github.com/user-attachments/assets/d0e6cef0-b887-41ce-ba1e-0828651da98e)
Or if you wanted to go all the way and make it super nice a Separate animal drops section would be perfect for this.

List of all the gameplay drops with strange names.
----------------------
Seal barter trades

![image](https://github.com/user-attachments/assets/41578aa6-70c7-43fd-a54a-bdee503854dc)
The thime music disk can only be gotten through this

--------------------------

Platupus digging

![image](https://github.com/user-attachments/assets/03eb8d57-04da-4c4f-b046-da7b43e55074)

This one is split into 2 different gameplay drops

one for when he has a Redstone block and one without I think it should be compacted into to one if possible it should have an icon like this to denote the change
![image](https://github.com/user-attachments/assets/cd87dfb7-7a9c-4b18-a96e-bdfd9eda7b37)

---------------------------------

Devil's hole pupfish Mossy cobble pecking. (btw this should be expanded on since it is the rarest mob)

![image](https://github.com/user-attachments/assets/6f2df97e-3ab8-45bf-8129-962485f45c4d)
Currently, this is just a slimeball under gameplay drops (this was very difficult to find also)

--------------------------------------

Super glider forging

![image](https://github.com/user-attachments/assets/635dfcb3-159a-4c89-92ca-68a525a7c8a1)

---------------------------------------

Ant eater raiding

![image](https://github.com/user-attachments/assets/53b8698d-0961-480e-9664-08d07773a99a)
the Gongylidia which is almost exclusively gotten by anteater raiding has an advancement attached to it also.

---------------------------------------

It should also be mentioned but this should also be renamed to sniffer digging

![image](https://github.com/user-attachments/assets/c79e8555-b986-4b30-b4de-7b90da4e0922)

**Comment by Guineapigboyx** [comment]
This is related but it does not even have a gameplay drops screen so I made it separate.

https://github.com/uthw/Mincemeat-2/issues/151

**Comment by uthw** [comment]
All of the changes you're talking about would probably require major changes to the source code of EMI Loot and Alex's Mobs. There's nothing I can do to fix this apart from adding information tabs to the more unique items with instruction on how to obtain them.

**Comment by Guineapigboyx** [comment]
Anteater raiding special item: Gongylidia

platypus digging special item: Fedora

Seal bartering special items: thime music disk, Technically a easy way to get coal without getting silk touch
