### ISSUE TITLE
Finding specific infinite veins can be very hard

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#158]
The main issue is that they spawn too infrequently most time a few hundred blocks away from each other. (feels like around 200-700)

This could be fixed by making it so the distance between infinite veins is shorter. or making it so certain biomes or dimensions can hold certain ores. like infinite gold is found in deserts emeralds in mountains lapis in oceans.

------------------------------
Also, I Know what I'm saying that these are too hard to find. I explored an entire continent and parts of 2 others, and I was not able to find All the different venis. for some materials, I only found 1 infinite vein in my entire time exploring. to name a few Redstone, gold, sulfur For some, I did not even find 1 infinite vein of, like arcane crystals.
![image](https://github.com/user-attachments/assets/6d79d158-374f-4546-b13f-6f53ae9130bb)
The ice maze counts as an ocean so sometimes it will look like 2 continents are connected.

This is also on top of how hard some of these would be to get since they could be hundreds of blocks away from a tower and thousands from my base.

**Comment by uthw** [comment]
This seems fine to me
