### ISSUE TITLE
Tugs stop moveing when too far away.

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#159]
This makes them worthless since they stop working when they are just a few blocks away. Also, I did register them which allegedly makes it so they are always loaded.

Video to show how they work.
https://github.com/user-attachments/assets/290e5bd0-f9e9-459e-9448-7c23aa0f32e7

**Comment by uthw** [comment]
Don't forget the bug template exists

**Comment by uthw** [comment]
And your video doesn't load

**Comment by Guineapigboyx** [comment]
It's super simple to reproduce it. Just send a tug on a route that goes a somewhat far distance and then just stand at the start location. you can see it stop moving.

**Comment by uthw** [comment]
Confirmed. This is most likely caused by some other mod messing with the chunk loading/AI of tugs. Will try to find the problematic mod later today. If you want to help out you can find the mod by testing if this issue exists on older versions and/or doing a binary search

**Comment by uthw** [comment]
We found the cause is Does Potato Tick. This has been removed for the next version
