### ISSUE TITLE
Ore excavation quest should incude diffrent teirs of drill

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#161]
### Affected quests

Tech level 1 | Ore excavation

### Does it prevent you from progressing through the quests?

No

### If this is a bug, does it only happen in the latest version?

None

### If this is not a bug, is it a suggestion/feature request?

Yes

### Describe the issue

There is the diamond and netherite drill but the quest only counts the iron drill as valid to complete the quest.

**Comment by uthw** [comment]
It's been done
