### ISSUE TITLE
Add EMI info for liquid mixing to make stones

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#164]
All 3 of the Create stone types all can be made with liquid mixing sorta like how you make a cobble stone generator.

Limestone
lava - honey

scoria
Lava - cholate

Vuridim
Lava - caramel milkshake

-----------------------------

Also, there should be a crafting recipe for at least limestone, like how Diorite has one since it needed to progress.
here is actually someone on reddit talking about it, https://www.reddit.com/r/QuarkMod/comments/glay6c/you_should_be_able_to_craft_new_stone_types_added/

**Comment by uthw** [comment]
The veridium recipe is from an addon called Dreams and Desires, which is not in the modpack currently. I did this for the first two though
