### ISSUE TITLE
Most types of wood can't make chests

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#167]
### Description

Right now you can only make chests out of just a few wood types

### Steps to Reproduce

Try to make a drift wood chest driftwood

### Involved Mods

Every compact
Any mod that adds chests

### Additional Context

Right now the only wood types that work are:
Base game
Better nether
Quark
Blue skies
Outer end
_also I guess sophisticated storage_

**Comment by uthw** [comment]
This is intentional, since I turned off the Every Compat quark module most variant chests won't be available unless a mod adds them itself. If you liked that feature I can turn on the quark module again for the next version.

**Comment by Guineapigboyx** [comment]
Yeah i would like it back since it was nice being able to make chests with any wood/make all the functional blocks out of any wood. _also at the moment there is no storage item that can work with any wood type_

Also I remember running into something where chests from every compact do not work with the sophisticated storage upgrades. (like the ones that you right click the chest with, like base to iron)

**Comment by uthw** [comment]
The quark module of every compat has been reenabled
