### ISSUE TITLE
Caves should insalate more from the heat/cold

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#169]
I'm burning to death at deep slate even when far from lava or heat sources. Just because I'm in a hot biome. This is new to this version, I have mostly tested this with heat in this version.

![image](https://github.com/user-attachments/assets/90476624-fe4d-4805-be13-f73c61cf0b17)

**Comment by uthw** [comment]
Cave insulation is already at the maximum magnitude, there is nothing I can do to fix this unfortunately
