### ISSUE TITLE
Sectioned quest lines

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#17]
You would unlock quest parts of quest trees as you did them kinda like tech Or how agriculture in mincemeat 1 where it shows you only one part until you progress far enough to see the other parts.

**Comment by Guineapigboyx** [comment]
A place in mincemeat 2 i think this could work well is magic
![image](https://github.com/uthw/Mincemeat-2/assets/143977088/6c6e313e-6680-45a7-ac44-e3edc2c172cc)

**Comment by uthw** [comment]
This has been added to tech level 1 and dimensional adventure. It already existed in overworld adventure prior to you opening this. I'll leave this open until I do it for more chapters

**Comment by uthw** [comment]
Oops i closed it on accident
