### ISSUE TITLE
Bestiary quests do not have the Notification popup in the corrner 

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#171]
I don't know if this is happening or not it needs more testing. It super inconsistent if it is happening since some mobs i do see it and other i don't.

It seams like it happens but i think its just someone else is finding the mob before me. I was getting confused since i did not get the notification thing for finding a cave centipede or a either of the troll quests and a few versions back it did not popup for the jumbo furnace.

------

_it is not formatted correctly because i tried to delete the issue since i don't think it is happening_

**Comment by uthw** [comment]
cave centipedes and other worm/snake mobs added by alex's mobs and ice and fire are split into multiple mobs (kinda like terraria with the eater of worlds), and you usually have to look at the head to get credit for the quest

you're probably just finding mobs a different player has already found in most cases, i've noticed that happen in my game
