### ISSUE TITLE
F3 menue has to much

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#2]
It makes my game lag and it can be hard to find something like light level that are Useful

**Comment by uthw** [comment]
Closing this since I have no way of fixing this right now due to the lack of mods to rebind F3 or remove lines from it

**Comment by uthw** [comment]
Actually, I'll keep this open so I remember later when the mod ports that I need in order to fix this.

**Comment by uthw** [comment]
Done
