### ISSUE TITLE
Expensive cobwebs

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#20]
for something this simple they are. You need to set up a honey farm and get good rng then 8 string just to make 1 cobweb. I like the idea of getting honey since it gives honey some purpose but i don't like how it takes 8 string.

![image](https://github.com/uthw/Mincemeat-2/assets/143977088/04090fed-272a-4bc7-bcbd-1d8d5c0d38c1)

**Comment by uthw** [comment]
The top recipe has been replaced with one that only needs 4 string
