### ISSUE TITLE
Quest tree confusion

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#22]
in the refined storage chapter there is a empty checkmark with no dependency for upgrading your storage.
![image](https://github.com/uthw/Mincemeat-2/assets/143977088/b3b1ed81-6945-436f-98ef-b9ed74381a68)

but there is also a quest in getting started for the same thing upgrading your storage.
![image](https://github.com/uthw/Mincemeat-2/assets/143977088/552731f1-5b8c-4751-9cef-064114ad1542)

I feel these should be connected and work by completing The quest on getting started to get the same quest finished in refined storage.

**Comment by uthw** [comment]
Thanks for the suggestion
