### ISSUE TITLE
Uneedd files in sever pack

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#27]
Random stuff
- att-dbug _(has nothing)_
- crashreports

Sever files.
You don't need these since you need to make your own neoforge sever since they can not be transfered ti different sytems without a installer. They can only overwrite and cruiopt being in there.

- local _(ftb chunks data)_
- banned ips
- banned players
- eula
- run.bat
- run.sh
- aever properties _(ridan)_
- usernamecache.json
- usercache.jason
- whitefish

Generated save files

- xeerominimap-common _(global waypoints)_
- xeerowprldmap-common _(chuncks that have been geenrerated)_
- deaths
- Dyanmic view distance mod _(locks max viee distsnce to 9)_

User jvm args i can go ethir way on since you do need them and they are not generated but not when updateing.

**Comment by uthw** [comment]
Those are all files you don't need if you already have a server pack from a previous version. Some of those files are necessary for servers so I'll add instructions for how to update a server instead.

**Comment by Guineapigboyx** [comment]
You can't use them at all none of them aprt from maybe eula and yvim will just not work.

You need to create a neoforged sever You just can't make one by downloading a zip
