### ISSUE TITLE
Preforlance Mod idea

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#28]
### distant horizons.

Distant horizons makes it so there is levels of detail in your rendered distance.

So if you have 64 or 128 chunk render distance you can have up to 12 be full res up to 32 be half res and 64 or even 128 be Two blocks is equivalent 1 block res.

Instead of using all the ram and resources to render all the trunks at the highest resolution and detail.

**Comment by uthw** [comment]
I tried distant horizons but it didn't seem to do anything when I enabled it

**Comment by Guineapigboyx** [comment]
You need to turn on the distant chunck generation in its own setting menue near. Video.

It took me a hot sec to find the tight settetings, but after you do, it works well.
