### ISSUE TITLE
More reasons to do magic

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#29]
Magic does not have nearly as many reasons to go thogh it ms quests than engineering.

Engineering gets you things like the motorized grappling hook and a lot of different building materials and tools.
While magic seems like about that you only go down just to do it. not to get anything like with engerning.

But sometimes feels like engineering is screaming. Out, for you to do it with all of its structures and different benefits while magic, almost feels like it's pushing you away or is a exclusive club with its complex mechanics and lack of reason to go into it.

I Kind of wish that magic had more reasons to do it. Or did not have a steep of us uphill start as it is right now.

I think if it's stayed as hard as it is right now to get into it it should give you some very strong abilities that help with resource athering

**Comment by uthw** [comment]
There are already lots of reasons to do magic, but they aren't advertised as heavily to you compared to tech. As I work on mincemeat 2 I'll add more recipes that need things like the enchanting apparatus and items from magic mods. I'll also add tips telling you what you can do with magic mods.

**Comment by uthw** [comment]
Added a few tips for Ars and decreased the cooldowns of all Iron's Spellbooks spells to make magic more powerful. I'll do more for it in the future
