### ISSUE TITLE
More progression walls

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#30]
I might Kick myself for saying this.

I kind of miss when just getting simple things.Took you having to progress through the mod pack. Like for example not getting diamonds was always a thing what would piss me off that I could not get them. But I think makeing it so I have to progress to unlock bases game stuff like diamonds made them more rewarding and also kick started progression into the mod pack.

I think walking things like diamonds made it so you have to kind of think out of the box for your gear also.

It made you kind of have to play the game differently since you're stuck with basically the bare minimum before you defeat the first few progression quests

**Comment by uthw** [comment]
I don't plan on using hard item restrictions in mincemeat 2 like there were in 1, but I am keeping the dimension restriction mechanic and many items are locked behind progressing through dimensions, beating bosses, and such.
