### ISSUE TITLE
More random quests

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#34]
You have some of these like the cooking and fishing quest but I'm more talking about quests that bring you down a random journey. Maybe to name some alrday in the modpack a bimome what has a miniboss like the ice maze or rotnot and his cave dungon.

These questions can also be things like the ordinary animals from mince one what are mostly there to add charm and flare. Like telling you about a mechnic you did not know before like centipede pants.

**Comment by uthw** [comment]
I think adding the bestiary solved this
