### ISSUE TITLE
Faster long distance travel

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#35]
Early game travel across oceans or oppress can be tiresome and hard at times. With the density of forests or cliffs of mountains and drag of oceans it makes  you wish sometimes for a viral travel option what is slow but safe and practical to go long distance.

A train track or a under sort of path would also be a good option for this Aldo. Or some way of getting back previous paths.

**Comment by uthw** [comment]
There are already hippocampi and submarines in the modpack but I added the Small Ships mod for a more early game sea travel option
