### ISSUE TITLE
Op atrutures and looting

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#36]
Some structures like villages can give you so much.Good though.That it'll undermine any other way of getting loot or valuables.

Like why go mineing when one camp or village can give you the same. Also some items like enchanted diamond tools or tons of food alrday make some of these locations even without the valuables very worth wile to go to. For even Is parts of houses like wind mills for create or trains for loot.

It seems like the best way to do anything is find a village and steal everything.

I think also having old peace structures hurt to law the other parts of the mod pack since you will not be finding new areas like dragons nests Alex caves houses or even blue skies houses since you will have most of what you need early on.

**Comment by uthw** [comment]
I added a mod that makes all structures rarer, hopefully this fixes your issue
