### ISSUE TITLE
Bring back the Progression quest chapter from Mincemeat 1

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#39]
IAnd miss me.I think of three different paths of there being.

Magic - what ever there is in those chapters
Tech - create and thermal
Battling - bosses a d equipment

I kind of wish that in the progression tab.There were goals to get to in each chapter a progression person for each chaptt. Almost like a benching quest tree

Like for tech what im the mos fimiler with you have one for makeing a working mixer. Maybe doing things like this will unlock different parts like makeing a windmill.

I feel like this is almost kind of gift side hprogressional paths to the normal progression maybe this could even link up with normal progression leaning into issue number 30's walls.

**Comment by uthw** [comment]
Added tech and magic progression trees in 0.4.4
