### ISSUE TITLE
To many forests

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#4]
There are too many forests I feel. like most of the time in mince one I felt there were more varied biomes but in minced 2 I feel that there are only forests. It's not a bad thing but I just think that there are just a few too many around the world in comparison to other biomes.

**Comment by uthw** [comment]
I see where you're coming from, I will remove Expanded Ecosphere as it seems like that makes forests more common compared to other types of biomes. I also added some new mods which offer a variety of fleshed-out biomes
