### ISSUE TITLE
Respawn safe zone/time.

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#40]
Whenever you use a grave school you have  a 80% chance of just dieing since you have no gear and have to hit your death maker a few times before getting your gear. I think a resistance buff after teleporting would be great since it would avoid instant death.

**Comment by uthw** [comment]
Fixed issues where you wouldn't get effects after using the grave scroll and you could get a scroll when a different player dies in multiplayer
