### ISSUE TITLE
Is more things in the ocean

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#42]
Is how currently as there is no a law in the oceans.

Other than ocean moments and revines and water caves you will not find structures or oht of water grapple fling points to travel high speed fast while exploring.

Though I couldn't kind of go either way unless if you're since also the water kind of feels like the highways admit me world sometimes. If you agree you can close this yo keep them solely for transport

**Comment by uthw** [comment]
I'll keep an eye out but there are already several mods that improve oceans in mincemeat 2
