### ISSUE TITLE
Epxotic matrials improved

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#43]
Lead and tin and nickel and even stupid stuff like minibar should be improved to be more useful but have more of a niche than being a jumping stone to diamond or small upgrades thats not do much.

I've always had a fun idea for a lead where it's super slow but does tons of damage. Even in spotting on weapon tree , then meet it till let it slow but they did not give any more buffs to offset the speed.

**Comment by uthw** [comment]
Spartan Weaponry items can have their attack damage customized but not their attack speed, so this isn't possible
