### ISSUE TITLE
Fall damge nulitying item quest

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#45]
i think there should be a quest for getting a item that gets rid of full damage that's not the paraglider or demuestra leaf.

This is for grappling hook since when grappling you still take fall damage even if you use those items.
And being able to swing without the fear of death is theblargest movement upgrade I think you could get in mincemeat 1 so it seems it would be useful as a quest.

**Comment by uthw** [comment]
Feather falling enchantment reduces fall damage and is well known due to being vanilla, I personally don't think this is necessary
