### ISSUE TITLE
Nub blocks can not be gotten/made

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#46]
Number blocks can't be made with a Stone cutter or mechanical saw.

**Comment by uthw** [comment]
![image](https://github.com/uthw/Mincemeat-2/assets/73855194/8edd0b37-08aa-490c-a078-fcbc8ebef0d8)
Should be good now

**Comment by Guineapigboyx** [comment]
i did show that before did you test it worked just wanna make sure
![image](https://github.com/uthw/Mincemeat-2/assets/143977088/b5a5fe79-26c5-4abb-8e22-525117dcac54)
