### ISSUE TITLE
underpowered hard to get items

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#48]
Some items like centipede leggings are so hard to get and then just a equivalent or Slightly stronger versión of a easier to get.

like centipede leggings require you going into a dangerous cave killing a dangerous mob for the outcome of getting diamonds pants with spiderman powers.

I feel i am like this should be almost overpowered and should be worth wasteing hours getting. Kind of like Terrarias rare items where they're extremely strong and basically break the game but because of their rarity it balances them out with the rest of the more common items.

**Comment by Guineapigboyx** [comment]
Some this does not to. A lot of the weapons are pretty balanced but it is more in the utilitys and gear what are more relevante to this

**Comment by uthw** [comment]
Many weapons from other dimensions have been made more powerful
