### ISSUE TITLE
You can find the "ender" in most chests

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#5]
the ender is a better than diamond sword you an get at the start of the game.

just thought to say that not since it is a pretty good sword that I found pretty early on into my world without looking to hard.
![Screenshot 2024-04-28 124656](https://github.com/uthw/Mincemeat-2/assets/143977088/5d866849-feef-4549-8ed9-43093571cb2d)

**Comment by uthw** [comment]
Removed The Ender from generated chests
