### ISSUE TITLE
Very Limited in how much time you're underwater

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#50]
You can only stay underwater for a few seconds before you start drowning gain a rid of a lot of the parts of Mint meat that are with water.

I think the o2 meter from better aquatic langth was a good amount of time. It gave you about a minute to stay underwater so you didn't have to only stay on top of the water or figure out ways to breathe underwater it also made it so you basically don't have to get water breathing to be able to experience things like ocean monuments or some water caves.

**Comment by uthw** [comment]
I don't think this is necessary, Vanilla Minecraft already has water breathing potions and the respiration enchant, and you can get water breathing using the scuba gear artifact, neptunium chestplate, or any piece of tide guardian armor all of which are fairly easy to obtain.
