### ISSUE TITLE
getting started always has a badge

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#52]
there is this quest what is always collectible
![image](https://github.com/uthw/Mincemeat-2/assets/143977088/c0b10514-04fd-4949-8334-d71d30ffa2de)

but then it will always have this little ! what means you did something
![image](https://github.com/uthw/Mincemeat-2/assets/143977088/ba36218c-5ae1-4fc4-af3f-396734078e87)

usually use this ! to see if i finished a quest but with it always there i have to binary search the quest to see if i finished them and it is a little annoying i wish there was a different way of doing of getting these books.

**Comment by uthw** [comment]
The eccentric tome quest has been moved into its own chapter.
