### ISSUE TITLE
Controlify crash

### ISSUE THREAD

**Issue by uthw** [uthw/Mincemeat-2#54]
[crash-2024-06-25_21.08.10-client.txt](https://github.com/user-attachments/files/15981030/crash-2024-06-25_21.08.10-client.txt)

For later I guess

**Comment by Guineapigboyx** [comment]
This is a different crash I belive from the one with pressing LT on the title screen or in f3.

**Comment by uthw** [comment]
Yes, that is true. It happened to me after sitting AFK in an offline world for around 20-30 minutes. It has only happened to me once.

**Comment by uthw** [comment]
This never happened a second time so I am assuming this fixed itself at some point
