### ISSUE TITLE
Over powered/super common food.

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#56]
These are the food I always seem to have and are eating.

I think lowering the amount of saturation or hunger or both on these food will balance them. Or changing how you could make these items like bread. Maybe even stack limits like you can only have 32 or 16 of one of these foods.

Here is a List of the common foods that are very powerful you can get with minimal effort. 

- steak (3 give you full hunger and saturation) found in like half of chests also)
- Bread (hay bales and also found in tons of chests)
- cooked mutton (hunter drops)
- Apples (tree chop mod drops a lot of them and found in chests)
- Cooked porkchop (I don't see them as much but I would imagine it has the same ishue as cooked mutton or steak)

- baked potato's (the least offending of them all they are common but most of the time you don't find them cooked and are rarer than the others in the list) I'm more pitting that one down because if the others were worse they would become the new best option)

**Comment by uthw** [comment]
All saturation values for food have been reduced. This affects all food and not just vanilla, but it does incentivize making high-saturation foods and not raiding random houses hopefully
