### ISSUE TITLE
Difficulty scaleing way to high in other dimensions

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#57]
Difficulty scaleing in blue skies feels unbalanced since when you arrive to blue skies you are most likely alrday over 1000 blocks out in one direction and blue skies enemies just being harder in general compared to normal mobs.

It makes most mobs basically unkillable unless you had pretty good gear since they will most of the time one shot you and your wooden and stone tools don't even stand a chance against them.

It Also it does not help that the first time you come to blue skies you bassicly have to just get lucky to be able to wood or stone since one spider could oneshot you putting youbin a oop of dieing and comeing back just to die again.

Also just for clarification this is mainly applying to when you come for the first time after you get armor and good weapons and are able to get to 0 0 it not as much of a ishue

**Comment by uthw** [comment]
Difficulty scaling in the Everbright, Everdawn, and End have all been decreased. Difficulty scaling in the Nether has increased, but it was set extremely low previously.
