### ISSUE TITLE
Fire bugs in blue skies are over powered 

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#58]
These bugs are super common in blue skies and will spit fire out fire all the time as long as they are within a few blocks of you or they will spit fire out when they hit you or you hit them. 

The main ishue is hoe much HP they have since they fly it's hard to hit them and dodge them makeing it difficult to kill them fast and they light you fire with a hard to gaurd attack what lights you on fire. They feel kinda over powered for the most common enemy in the ever dawn to me at least. They still stay a issue even after you get better gear also since they are so common and take a bit to kill and also still are able to deal a lot of damge to the player even with good gear since they deal fire damge.

**Comment by uthw** [comment]
Health and damage of Emberbacks decreased
