### ISSUE TITLE
Sling shot has very low max durability

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#60]
It only has 384 what if you are planing to use it like the torch launcher form mincemeat 1. That means you will need to bring a ton of touches but and also  get a high level unbreaking on it so it does not just break after one trip in cave.

**Comment by uthw** [comment]
Sounds like you need to use the slingshot more sparingly since it is not a torch launcher. Also, you can mitigate this by bringing multiple slingshots into the caves.
