### ISSUE TITLE
Quartz is super hard/rare to get pre nether

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#61]
Ok this one does make sense but it is a bit annoying since you need quartz for a lot of Redstone things in minecraft/mincemeat and since the nether is so far in to progression it basically locks you off form a lot of Redstone devices unless you know how to make versions of them without quartz like piston Redstone clocks.

There is a way to get quartz but it pretty hard to get since at least from my testing it is a 1/1000 chance of getting 1 form the extractor. 
*If you could change the odds for the extractor that would fix this.*

**Comment by uthw** [comment]
Pressing diorite now has a small chance of yielding nether quartz.
