### ISSUE TITLE
Quest for basic movement/keybinds

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#64]
I think there should be a quest what covers basic monverbility like dodges and how to preform wall jumps. Becuase other wise they would be hidden mechanics to new player if they did not know already about the mechanics or the new player looked at the hot keys and knew the mods function.

**Comment by uthw** [comment]
This is a good idea and something that was in Mincemeat 1 if I recall

**Comment by uthw** [comment]
The quest is in Overworld Adventure
