### ISSUE TITLE
Tinker workshop house is super laggy

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#65]
It is the house what gives you the inker construct advancment and it makes the game lag like crazy if you are near it like put you down to 1 Fps laggy.

It laggs a ton if you are nearby this house for a few minutes I have noticed.

**Comment by Guineapigboyx** [comment]
here is a comparison where i am respawning in the tinkers construct house and in a different nearby structure.

tinker construct
https://youtu.be/_q7xhsgO4E0

other structure
https://youtu.be/6uA3V3WGpHQ

**Comment by uthw** [comment]
Tinker's Workshop has been made rarer. This fix may not apply to RTF worlds, so we'll need to test it.
