### ISSUE TITLE
Enable lookup history [EMI]

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#66]
I was poking around in EMI config since i was trying to find a way to sort it by mod. when i was looking in the config found a subpannels option, and a History page option.
![image](https://github.com/user-attachments/assets/c525912d-8992-4012-b783-38dc4185eaa4)

I think adding a history page would help greatly since I find myself sometimes needing to create a lot of the same items or needing to make a bunch of different items to make one item.
![image](https://github.com/user-attachments/assets/9efce860-4c1e-447a-bb10-7d0d2fb57855)

I think adding a panel like this would help greatly with some of these items or just remembering how something was made without needing to search it up again.

**Comment by uthw** [comment]
Done
