### ISSUE TITLE
sotage drawers in alrday exists in sophisticated storage

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#67]
in sophisticated storage there is the limited barrel what works identical to the storage drawers mod. _It even has the same function with Shift clicking takes a stack and punching takes 1 and even the right click menu._ I also believe removing the storage drawers mod would help with ram since removing it would get rid of over 900 blocks. _what is more than natures spirit_
![image](https://github.com/user-attachments/assets/a0109072-d295-475b-b239-6187366de591)
 
picture of the limited barrel
![image](https://github.com/user-attachments/assets/82ce10c9-80d3-4081-a64d-fc0289386911)

**Comment by uthw** [comment]
Done
