### ISSUE TITLE
Fov getting changed when changeing from borderless to widnowed

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#68]
I have also noticed this happening at other times like just clicking off or changing a different setting.
it is pretty inconsistent also and doesn't happen every time.

I put a video of it happening
https://github.com/user-attachments/assets/589e269b-32ec-4717-adb1-aea6e526825d

**Comment by Guineapigboyx** [comment]
This is most likely a mod issue and can't be fixed but it happens a lot so i thought to put it in here, for if a issue was made somewhere else.

**Comment by uthw** [comment]
I can't reproduce this. My fov does not change when going from windowed to borderless.
