### ISSUE TITLE
Non war forged tetra weapons do not have better combat

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#69]
Some weapons do not have better combat in tetra such as hammers or knifes and a most tools like adzes. tho the tools can be fixed by warforgeing them.

**Comment by Guineapigboyx** [comment]
After i put this issue down i found the real issue. What it is when there is a weapon what has a "weapon version" it will only have better combat when in its weapon version. so like a normal knife is counted as a tool but a throwing knife is a weapon so its does have better combat. or a warhammer works but a normal hammer does not.

on the modrinth website for Tetratic Combat Expanded it says it can be fixed by editing the config.
https://modrinth.com/mod/tetratic-combat-expanded

**Comment by uthw** [comment]
Made a datapack with the tetra.json file, which will hopefully fix it
