### ISSUE TITLE
Being able to mark off compleate quests

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#70]
Just adding a check mark to the rewards section of every quest (or at least the ones in baptistery and early quests of each chapter like making a water wheel). Also a money system like mince meat 1 could work also, but at least for now that would most likely take a while to implement)

**Comment by uthw** [comment]
I'm going to close this since it's pretty much asking for the same thing as #24, and closing that issue would close this one too. Quest rewards are a planned feature but will likely not be implemented for a while due to how tedious I find them.
