### ISSUE TITLE
Expanded Enchanter and/or Enchanting Apparatus

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#73]
Adding more Books you can Create with the enchanter. If possible every enchantment.
I also think this would be worth since it would make a alternate to enchanting with RNG or getting tons of levels.

_I could make what the items would requirement would be if you don't feel like making all of them_

**Comment by uthw** [comment]
i added recipes for enchantments from apotheosis, ensorcellation, majrusz's, enigmatic legacy, allurement, and feathers. i skipped some mods that add more niche enchants like ender io, spartan weaponry, and alex's mobs but if you really want them i'll add them later

**Comment by uthw** [comment]
note this is for apparatus only, i think the enchanter is balanced only having vanilla enchantments and would be too powerful if you could get any enchantment that easily
