### ISSUE TITLE
Nerf Apotheosis diamond tool trades with wandering trader

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#78]
As fun as they are way to strong for just being able to be gotten with a few emeralds and good rng.

I like the idea of them being traded for, and giving a use to the traveling Merchant. Maybe possibly they can use some other item that you have to get to be able to buy them.

**Comment by uthw** [comment]
The wandering trader still sells these tools, but they are all made of materials other than diamonds which are harder to obtain. Most require leaving the overworld to obtain, so if playing optimally you'd have that level of tools when you're able to buy the items.
