### ISSUE TITLE
garve scroll recipe was not added

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#8]
assuming you can make it but I remember you said you were going to be a able to in the new versiom

I think also a quest would be a good idea to add or something what would tell you of how you would make one.

**Comment by uthw** [comment]
Can you send me your `kubejs/server_scripts/recipes/minecraft/crafting_shapeless.js`?

**Comment by uthw** [comment]
That's my mistake actually, to fix this you need to copy the `menu` folder from 0.1.0 into 0.2.0
