### ISSUE TITLE
All Thermal alloy's are uncraftible

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#81]
It Seams alloys that need a alloy smelter to be made have all been replaced with Needing a blend but the blends do not have a recipe what is not Using the alloy its self. I did also check all the other options for making the alloys but there was nothing.
_Or at least in EMI it does not have any of them_

Currently
![image](https://github.com/user-attachments/assets/f455af3a-067b-4bf8-8aef-b122581f1134)

What it should be
![image](https://github.com/user-attachments/assets/52ed97fa-f4d8-4798-af42-6eaa217f3b52)

**Comment by uthw** [comment]
Wrong
