### ISSUE TITLE
Color codeing chests is broken

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#87]
You are not able to Dye Chests by just putting the chest in the center of a crafting table and putting dye on the top or bottom or sides.

Also The quest require a normal barrel or normal chests instead of any of the different versions.

**Comment by uthw** [comment]
The recipe is not broken, the quest is just misleading. Sophisticated Storage does not support color coding chests/barrels from vanilla or other mods. I've made this clear in the quest description for Color Coding and changed the requirement to be a chest or barrel from Sophisticated Storage.
