### ISSUE TITLE
Why is there so many creaper spawns

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#91]
I have noticed this for the last few versions, but there are so many creaper spawns. Like disproportionate ratio of creapers to other mobs.

I mainly notice this on the surface at night and not as much in caves. Possibly it has something to do with how far they can see the player.

**Comment by uthw** [comment]
![image](https://github.com/user-attachments/assets/e2b0922d-4691-424b-8ca7-46c830bb8d78)
Looks normal to me. I tested this by setting the difficulty to peaceful and then changing it to hard in a superflat world.

**Comment by uthw** [comment]
This is most likely just random chance. I'm closing this issue but will reopen it if you give evidence that you're consistently seeing a large amount of creepers compared to other mobs.
