### ISSUE TITLE
Brilliant fibers quest has vague wording

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#92]
It says to right click leaves. Right click them with what I was spam clicking leaves and nothing was happing.

In EMI it says you can make them with a enchanting aptus so if that the way you make them that should be explained.

**Comment by uthw** [comment]
The description was telling you to right click the leaves using the fiber. I added this to the subtitle of the quest.

**Comment by Guineapigboyx** [comment]
I was talking about how you get the brilliant fibers. Not what you do with them.
