### ISSUE TITLE
Key binds in defaultoptions.txt are outdated

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#94]
Mainly the important keybinds that you would always want.

- Xaneos world map insted of ftb map
- Crawl
- Zoom (I think it does not work since it conflicts with other keybinds)

There a few others most likely

**Comment by uthw** [comment]
I couldn't reproduce your issues with opening the wrong minimap, crawl being unbound, and the zoom conflicitng; all three of those were fine. I tested this by deleting my options.txt and letting KubeJS create one based on options I set several versions ago. Therefore, these may be happening if you're importing options from an older version of the modpack.

However, I went ahead and changed the Simple Voice Chat bindings so they don't conflict with other mods, fixed ping and crawl being on the same button, and turned off subtitles by default.
