### ISSUE TITLE
Lanterns/belt slot

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#96]
Becuase lanturns should always be on your belt (becuase thye are basicly a off hand torch without takeing your off hand) I think there should be another belt slot. Like what you did with the back slot and backpack.

**Comment by uthw** [comment]
I think it's fair that way. Dynamic lighting is a convenience, in order to have it you need to either give up your offhand or your belt slot. I made an exception with back slots because they're so fundamental to large modpacks that it's hard to explore without one equipped at all times.
