### ISSUE TITLE
Integrated villages

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#97]
They spawn in some many chests with good loot and tons of viligers what lag the game. (On lower end device's to a extreme level.) They should be removed or made significantly rarer.

**Comment by uthw** [comment]
Made modded villages less frequent, with integrated villages moreso than the rest. I will agree that integrated villages were overshadowing all other village types. If they become too common/rare, comment on this issue and I will reopen it.
